package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ActividadPorCiclo generated by hbm2java
 */
@Entity
@Table(name = "actividad_por_ciclo", catalog = "academitics")
public class ActividadPorCiclo implements java.io.Serializable {

	private String idActividadPorCiclo;
	private String cicloEscolar;
	private int idActividadCurso;
	private int idCiclo;

	public ActividadPorCiclo() {
	}

	public ActividadPorCiclo(String idActividadPorCiclo, int idActividadCurso,
			int idCiclo) {
		this.idActividadPorCiclo = idActividadPorCiclo;
		this.idActividadCurso = idActividadCurso;
		this.idCiclo = idCiclo;
	}

	public ActividadPorCiclo(String idActividadPorCiclo, String cicloEscolar,
			int idActividadCurso, int idCiclo) {
		this.idActividadPorCiclo = idActividadPorCiclo;
		this.cicloEscolar = cicloEscolar;
		this.idActividadCurso = idActividadCurso;
		this.idCiclo = idCiclo;
	}

	@Id
	@Column(name = "id_actividad_por_ciclo", unique = true, nullable = false, length = 10)
	public String getIdActividadPorCiclo() {
		return this.idActividadPorCiclo;
	}

	public void setIdActividadPorCiclo(String idActividadPorCiclo) {
		this.idActividadPorCiclo = idActividadPorCiclo;
	}

	@Column(name = "ciclo_escolar", length = 10)
	public String getCicloEscolar() {
		return this.cicloEscolar;
	}

	public void setCicloEscolar(String cicloEscolar) {
		this.cicloEscolar = cicloEscolar;
	}

	@Column(name = "id_actividad_curso", nullable = false)
	public int getIdActividadCurso() {
		return this.idActividadCurso;
	}

	public void setIdActividadCurso(int idActividadCurso) {
		this.idActividadCurso = idActividadCurso;
	}

	@Column(name = "id_ciclo", nullable = false)
	public int getIdCiclo() {
		return this.idCiclo;
	}

	public void setIdCiclo(int idCiclo) {
		this.idCiclo = idCiclo;
	}

}
