package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ActividadPorPeriodo generated by hbm2java
 */
@Entity
@Table(name = "actividad_por_periodo", catalog = "academitics")
public class ActividadPorPeriodo implements java.io.Serializable {

	private int idActividadPorPeriodo;
	private Long nota;
	private String idActividadPorCiclo;
	private int idActividadPeriodo;
	private int idActividadCurso;

	public ActividadPorPeriodo() {
	}

	public ActividadPorPeriodo(int idActividadPorPeriodo,
			String idActividadPorCiclo, int idActividadPeriodo,
			int idActividadCurso) {
		this.idActividadPorPeriodo = idActividadPorPeriodo;
		this.idActividadPorCiclo = idActividadPorCiclo;
		this.idActividadPeriodo = idActividadPeriodo;
		this.idActividadCurso = idActividadCurso;
	}

	public ActividadPorPeriodo(int idActividadPorPeriodo, Long nota,
			String idActividadPorCiclo, int idActividadPeriodo,
			int idActividadCurso) {
		this.idActividadPorPeriodo = idActividadPorPeriodo;
		this.nota = nota;
		this.idActividadPorCiclo = idActividadPorCiclo;
		this.idActividadPeriodo = idActividadPeriodo;
		this.idActividadCurso = idActividadCurso;
	}

	@Id
	@Column(name = "id_actividad_por_periodo", unique = true, nullable = false)
	public int getIdActividadPorPeriodo() {
		return this.idActividadPorPeriodo;
	}

	public void setIdActividadPorPeriodo(int idActividadPorPeriodo) {
		this.idActividadPorPeriodo = idActividadPorPeriodo;
	}

	@Column(name = "nota", precision = 10, scale = 0)
	public Long getNota() {
		return this.nota;
	}

	public void setNota(Long nota) {
		this.nota = nota;
	}

	@Column(name = "id_actividad_por_ciclo", nullable = false, length = 10)
	public String getIdActividadPorCiclo() {
		return this.idActividadPorCiclo;
	}

	public void setIdActividadPorCiclo(String idActividadPorCiclo) {
		this.idActividadPorCiclo = idActividadPorCiclo;
	}

	@Column(name = "id_actividad_periodo", nullable = false)
	public int getIdActividadPeriodo() {
		return this.idActividadPeriodo;
	}

	public void setIdActividadPeriodo(int idActividadPeriodo) {
		this.idActividadPeriodo = idActividadPeriodo;
	}

	@Column(name = "id_actividad_curso", nullable = false)
	public int getIdActividadCurso() {
		return this.idActividadCurso;
	}

	public void setIdActividadCurso(int idActividadCurso) {
		this.idActividadCurso = idActividadCurso;
	}

}
