package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ActividadPeriodo generated by hbm2java
 */
@Entity
@Table(name = "actividad_periodo", catalog = "academitics")
public class ActividadPeriodo implements java.io.Serializable {

	private Integer idActividadPeriodo;
	private Integer sucursal;
	private Boolean estado;
	private BigDecimal notaPeriodo;
	private Boolean eliminado;
	private int idAsignacionCurso;
	private int idPeriodo;

	public ActividadPeriodo() {
	}

	public ActividadPeriodo(int idAsignacionCurso, int idPeriodo) {
		this.idAsignacionCurso = idAsignacionCurso;
		this.idPeriodo = idPeriodo;
	}

	public ActividadPeriodo(Integer sucursal, Boolean estado,
			BigDecimal notaPeriodo, Boolean eliminado, int idAsignacionCurso,
			int idPeriodo) {
		this.sucursal = sucursal;
		this.estado = estado;
		this.notaPeriodo = notaPeriodo;
		this.eliminado = eliminado;
		this.idAsignacionCurso = idAsignacionCurso;
		this.idPeriodo = idPeriodo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_actividad_periodo", unique = true, nullable = false)
	public Integer getIdActividadPeriodo() {
		return this.idActividadPeriodo;
	}

	public void setIdActividadPeriodo(Integer idActividadPeriodo) {
		this.idActividadPeriodo = idActividadPeriodo;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "nota_periodo", precision = 18)
	public BigDecimal getNotaPeriodo() {
		return this.notaPeriodo;
	}

	public void setNotaPeriodo(BigDecimal notaPeriodo) {
		this.notaPeriodo = notaPeriodo;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "id_asignacion_curso", nullable = false)
	public int getIdAsignacionCurso() {
		return this.idAsignacionCurso;
	}

	public void setIdAsignacionCurso(int idAsignacionCurso) {
		this.idAsignacionCurso = idAsignacionCurso;
	}

	@Column(name = "id_periodo", nullable = false)
	public int getIdPeriodo() {
		return this.idPeriodo;
	}

	public void setIdPeriodo(int idPeriodo) {
		this.idPeriodo = idPeriodo;
	}

}
