package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ActividadesCurso generated by hbm2java
 */
@Entity
@Table(name = "actividades_curso", catalog = "academitics")
public class ActividadesCurso implements java.io.Serializable {

	private Integer idActividadCurso;
	private Integer sucursal;
	private Boolean eliminado;
	private Boolean estado;
	private BigDecimal porcentaje;
	private String nombre;

	public ActividadesCurso() {
	}

	public ActividadesCurso(Integer sucursal, Boolean eliminado,
			Boolean estado, BigDecimal porcentaje, String nombre) {
		this.sucursal = sucursal;
		this.eliminado = eliminado;
		this.estado = estado;
		this.porcentaje = porcentaje;
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_actividad_curso", unique = true, nullable = false)
	public Integer getIdActividadCurso() {
		return this.idActividadCurso;
	}

	public void setIdActividadCurso(Integer idActividadCurso) {
		this.idActividadCurso = idActividadCurso;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "porcentaje", precision = 18)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
