package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AlumnoEncargado generated by hbm2java
 */
@Entity
@Table(name = "alumno_encargado", catalog = "academitics")
public class AlumnoEncargado implements java.io.Serializable {

	private AlumnoEncargadoId id;
	private Date fechaModificacion;
	private Date fechaEliminacion;
	private Date fechaAdicion;
	private String usuarioAdiciona;
	private String usuarioElimina;
	private String usuarioModifica;
	private Boolean eliminado;
	private Integer sucursal;
	private Boolean esEncargado;
	private Integer idPueblo;

	public AlumnoEncargado() {
	}

	public AlumnoEncargado(AlumnoEncargadoId id) {
		this.id = id;
	}

	public AlumnoEncargado(AlumnoEncargadoId id, Date fechaModificacion,
			Date fechaEliminacion, Date fechaAdicion, String usuarioAdiciona,
			String usuarioElimina, String usuarioModifica, Boolean eliminado,
			Integer sucursal, Boolean esEncargado, Integer idPueblo) {
		this.id = id;
		this.fechaModificacion = fechaModificacion;
		this.fechaEliminacion = fechaEliminacion;
		this.fechaAdicion = fechaAdicion;
		this.usuarioAdiciona = usuarioAdiciona;
		this.usuarioElimina = usuarioElimina;
		this.usuarioModifica = usuarioModifica;
		this.eliminado = eliminado;
		this.sucursal = sucursal;
		this.esEncargado = esEncargado;
		this.idPueblo = idPueblo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idAnio", column = @Column(name = "id_anio", nullable = false, length = 2)),
			@AttributeOverride(name = "idCorrelativo", column = @Column(name = "id_correlativo", nullable = false)),
			@AttributeOverride(name = "idCarrera", column = @Column(name = "id_carrera", nullable = false)),
			@AttributeOverride(name = "idNivel", column = @Column(name = "id_nivel", nullable = false)),
			@AttributeOverride(name = "idFamiliar", column = @Column(name = "id_familiar", nullable = false)),
			@AttributeOverride(name = "idAlumnoFamiliar", column = @Column(name = "id_alumno_familiar", nullable = false)) })
	public AlumnoEncargadoId getId() {
		return this.id;
	}

	public void setId(AlumnoEncargadoId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eliminacion", length = 19)
	public Date getFechaEliminacion() {
		return this.fechaEliminacion;
	}

	public void setFechaEliminacion(Date fechaEliminacion) {
		this.fechaEliminacion = fechaEliminacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Column(name = "usuario_elimina", length = 10)
	public String getUsuarioElimina() {
		return this.usuarioElimina;
	}

	public void setUsuarioElimina(String usuarioElimina) {
		this.usuarioElimina = usuarioElimina;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "es_encargado")
	public Boolean getEsEncargado() {
		return this.esEncargado;
	}

	public void setEsEncargado(Boolean esEncargado) {
		this.esEncargado = esEncargado;
	}

	@Column(name = "id_pueblo")
	public Integer getIdPueblo() {
		return this.idPueblo;
	}

	public void setIdPueblo(Integer idPueblo) {
		this.idPueblo = idPueblo;
	}

}
