package com.academitics.mapeo;

// Generated 31/07/2015 07:24:00 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.academitics.util.Variables;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name = "alumno", catalog = "academitics")
public class Alumno implements java.io.Serializable {

	private AlumnoId id;
	private Date fechaEliminacion;
	private String usuarioElimina;
	private Boolean huerfanoPadre;
	private Boolean huerfanoMadre;
	private String pueblo;
	private String comunidadEtnica;
	private Integer telefonoEmergencia;
	private String nacionalidad;
	private String lateralidad;
	private String partidaNacimiento;
	private Date fechaModficacion;
	private Date fechaAdicion;
	private String usuarioAdiciona;
	private String usuarioModifica;
	private Integer sucursal;
	private Boolean tipoAlumno;
	private Boolean primerIngreso;
	private Boolean conocimientoComputacion;
	private String observacionEncargado;
	private BigDecimal saldo;
	private Boolean solvente;
	private Boolean eliminado;
	private String foto;
	private String codigoMineduc;
	private Boolean estado;
	private String direccionActual;
	private String direccionNacimiento;
	private Integer telefono;
	private Integer celular;
	private Boolean genero;
	private String correo;
	private Date fechaNacimiento;
	private String pasaporte;
	private String cui;
	private String estadoAlumno;
	private String nombres;
	private String apellidos;
	private int idComunidadEtnica;
	private int idPueblo;
	private int idEstadoCivil;
	private int idTipoAlumno;

	public Alumno() {			
	}
	
	public Alumno(String idAnio,int idCarrera, int idNivel) {
		eliminado = false;
		fechaAdicion = new Date();
		usuarioAdiciona = Variables.usuarioSesion;
		sucursal = Variables.sucursal;
		id = new AlumnoId(idAnio, idCarrera, idNivel);		
	}

	public Alumno(AlumnoId id, int idComunidadEtnica, int idPueblo,
			int idEstadoCivil, int idTipoAlumno) {
		this.id = id;
		this.idComunidadEtnica = idComunidadEtnica;
		this.idPueblo = idPueblo;
		this.idEstadoCivil = idEstadoCivil;
		this.idTipoAlumno = idTipoAlumno;
	}

	public Alumno(AlumnoId id, Date fechaEliminacion, String usuarioElimina,
			Boolean huerfanoPadre, Boolean huerfanoMadre, String pueblo,
			String comunidadEtnica, Integer telefonoEmergencia,
			String nacionalidad, String lateralidad, String partidaNacimiento,
			Date fechaModficacion, Date fechaAdicion, String usuarioAdiciona,
			String usuarioModifica, Integer sucursal, Boolean tipoAlumno,
			Boolean primerIngreso, Boolean conocimientoComputacion,
			String observacionEncargado, BigDecimal saldo, Boolean solvente,
			Boolean eliminado, String foto, String codigoMineduc,
			Boolean estado, String direccionActual, String direccionNacimiento,
			Integer telefono, Integer celular, Boolean genero, String correo,
			Date fechaNacimiento, String pasaporte, String cui,
			String estadoAlumno, String nombres, String apellidos,
			int idComunidadEtnica, int idPueblo, int idEstadoCivil,
			int idTipoAlumno) {
		this.id = id;
		this.fechaEliminacion = fechaEliminacion;
		this.usuarioElimina = usuarioElimina;
		this.huerfanoPadre = huerfanoPadre;
		this.huerfanoMadre = huerfanoMadre;
		this.pueblo = pueblo;
		this.comunidadEtnica = comunidadEtnica;
		this.telefonoEmergencia = telefonoEmergencia;
		this.nacionalidad = nacionalidad;
		this.lateralidad = lateralidad;
		this.partidaNacimiento = partidaNacimiento;
		this.fechaModficacion = fechaModficacion;
		this.fechaAdicion = fechaAdicion;
		this.usuarioAdiciona = usuarioAdiciona;
		this.usuarioModifica = usuarioModifica;
		this.sucursal = sucursal;
		this.tipoAlumno = tipoAlumno;
		this.primerIngreso = primerIngreso;
		this.conocimientoComputacion = conocimientoComputacion;
		this.observacionEncargado = observacionEncargado;
		this.saldo = saldo;
		this.solvente = solvente;
		this.eliminado = eliminado;
		this.foto = foto;
		this.codigoMineduc = codigoMineduc;
		this.estado = estado;
		this.direccionActual = direccionActual;
		this.direccionNacimiento = direccionNacimiento;
		this.telefono = telefono;
		this.celular = celular;
		this.genero = genero;
		this.correo = correo;
		this.fechaNacimiento = fechaNacimiento;
		this.pasaporte = pasaporte;
		this.cui = cui;
		this.estadoAlumno = estadoAlumno;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.idComunidadEtnica = idComunidadEtnica;
		this.idPueblo = idPueblo;
		this.idEstadoCivil = idEstadoCivil;
		this.idTipoAlumno = idTipoAlumno;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idAnio", column = @Column(name = "id_anio", nullable = false, length = 2)),
			@AttributeOverride(name = "idCorrelativo", column = @Column(name = "id_correlativo", nullable = false)),
			@AttributeOverride(name = "idCarrera", column = @Column(name = "id_carrera", nullable = false)),
			@AttributeOverride(name = "idNivel", column = @Column(name = "id_nivel", nullable = false)) })
	public AlumnoId getId() {
		return this.id;
	}

	public void setId(AlumnoId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eliminacion", length = 19)
	public Date getFechaEliminacion() {
		return this.fechaEliminacion;
	}

	public void setFechaEliminacion(Date fechaEliminacion) {
		this.fechaEliminacion = fechaEliminacion;
	}

	@Column(name = "usuario_elimina", length = 10)
	public String getUsuarioElimina() {
		return this.usuarioElimina;
	}

	public void setUsuarioElimina(String usuarioElimina) {
		this.usuarioElimina = usuarioElimina;
	}

	@Column(name = "huerfano_padre")
	public Boolean getHuerfanoPadre() {
		return this.huerfanoPadre;
	}

	public void setHuerfanoPadre(Boolean huerfanoPadre) {
		this.huerfanoPadre = huerfanoPadre;
	}

	@Column(name = "huerfano_madre")
	public Boolean getHuerfanoMadre() {
		return this.huerfanoMadre;
	}

	public void setHuerfanoMadre(Boolean huerfanoMadre) {
		this.huerfanoMadre = huerfanoMadre;
	}

	@Column(name = "pueblo", length = 50)
	public String getPueblo() {
		return this.pueblo;
	}

	public void setPueblo(String pueblo) {
		this.pueblo = pueblo;
	}

	@Column(name = "comunidad_etnica", length = 30)
	public String getComunidadEtnica() {
		return this.comunidadEtnica;
	}

	public void setComunidadEtnica(String comunidadEtnica) {
		this.comunidadEtnica = comunidadEtnica;
	}

	@Column(name = "telefono_emergencia")
	public Integer getTelefonoEmergencia() {
		return this.telefonoEmergencia;
	}

	public void setTelefonoEmergencia(Integer telefonoEmergencia) {
		this.telefonoEmergencia = telefonoEmergencia;
	}

	@Column(name = "nacionalidad", length = 40)
	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	@Column(name = "lateralidad", length = 50)
	public String getLateralidad() {
		return this.lateralidad;
	}

	public void setLateralidad(String lateralidad) {
		this.lateralidad = lateralidad;
	}

	@Column(name = "partida_nacimiento", length = 15)
	public String getPartidaNacimiento() {
		return this.partidaNacimiento;
	}

	public void setPartidaNacimiento(String partidaNacimiento) {
		this.partidaNacimiento = partidaNacimiento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modficacion", length = 19)
	public Date getFechaModficacion() {
		return this.fechaModficacion;
	}

	public void setFechaModficacion(Date fechaModficacion) {
		this.fechaModficacion = fechaModficacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "tipo_alumno")
	public Boolean getTipoAlumno() {
		return this.tipoAlumno;
	}

	public void setTipoAlumno(Boolean tipoAlumno) {
		this.tipoAlumno = tipoAlumno;
	}

	@Column(name = "primer_ingreso")
	public Boolean getPrimerIngreso() {
		return this.primerIngreso;
	}

	public void setPrimerIngreso(Boolean primerIngreso) {
		this.primerIngreso = primerIngreso;
	}

	@Column(name = "conocimiento_computacion")
	public Boolean getConocimientoComputacion() {
		return this.conocimientoComputacion;
	}

	public void setConocimientoComputacion(Boolean conocimientoComputacion) {
		this.conocimientoComputacion = conocimientoComputacion;
	}

	@Column(name = "observacion_encargado")
	public String getObservacionEncargado() {
		return this.observacionEncargado;
	}

	public void setObservacionEncargado(String observacionEncargado) {
		this.observacionEncargado = observacionEncargado;
	}

	@Column(name = "saldo", precision = 15)
	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	@Column(name = "solvente")
	public Boolean getSolvente() {
		return this.solvente;
	}

	public void setSolvente(Boolean solvente) {
		this.solvente = solvente;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "foto")
	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	@Column(name = "codigo_mineduc", length = 30)
	public String getCodigoMineduc() {		
		return this.codigoMineduc;
	}

	public void setCodigoMineduc(String codigoMineduc) {
		this.codigoMineduc = codigoMineduc;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "direccion_actual")
	public String getDireccionActual() {
		return this.direccionActual;
	}

	public void setDireccionActual(String direccionActual) {
		this.direccionActual = direccionActual;
	}

	@Column(name = "direccion_nacimiento")
	public String getDireccionNacimiento() {
		return this.direccionNacimiento;
	}

	public void setDireccionNacimiento(String direccionNacimiento) {
		this.direccionNacimiento = direccionNacimiento;
	}

	@Column(name = "telefono")
	public Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	@Column(name = "celular")
	public Integer getCelular() {
		return this.celular;
	}

	public void setCelular(Integer celular) {
		this.celular = celular;
	}

	@Column(name = "genero")
	public Boolean getGenero() {
		return this.genero;
	}

	public void setGenero(Boolean genero) {
		this.genero = genero;
	}

	@Column(name = "correo", length = 150)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_nacimiento", length = 19)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "pasaporte", length = 20)
	public String getPasaporte() {
		return this.pasaporte;
	}

	public void setPasaporte(String pasaporte) {
		this.pasaporte = pasaporte;
	}

	@Column(name = "cui", length = 15)
	public String getCui() {
		return this.cui;
	}

	public void setCui(String cui) {
		this.cui = cui;
	}

	@Column(name = "estado_alumno", length = 50)
	public String getEstadoAlumno() {
		return this.estadoAlumno;
	}

	public void setEstadoAlumno(String estadoAlumno) {
		this.estadoAlumno = estadoAlumno;
	}

	@Column(name = "nombres", length = 250)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "apellidos", length = 200)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "id_comunidad_etnica", nullable = false)
	public int getIdComunidadEtnica() {
		return this.idComunidadEtnica;
	}

	public void setIdComunidadEtnica(int idComunidadEtnica) {
		this.idComunidadEtnica = idComunidadEtnica;
	}

	@Column(name = "id_pueblo", nullable = false)
	public int getIdPueblo() {
		return this.idPueblo;
	}

	public void setIdPueblo(int idPueblo) {
		this.idPueblo = idPueblo;
	}

	@Column(name = "id_estado_civil", nullable = false)
	public int getIdEstadoCivil() {
		return this.idEstadoCivil;
	}

	public void setIdEstadoCivil(int idEstadoCivil) {
		this.idEstadoCivil = idEstadoCivil;
	}

	@Column(name = "id_tipo_alumno", nullable = false)
	public int getIdTipoAlumno() {
		return this.idTipoAlumno;
	}

	public void setIdTipoAlumno(int idTipoAlumno) {
		this.idTipoAlumno = idTipoAlumno;
	}

}
