package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AsignacionCurso generated by hbm2java
 */
@Entity
@Table(name = "asignacion_curso", catalog = "academitics")
public class AsignacionCurso implements java.io.Serializable {

	private Integer idAsignacionCurso;
	private Date fechaEliminacion;
	private Date fechaAdicion;
	private Date fechaModificacion;
	private String usuarioElimina;
	private String usuarioModifica;
	private String usuarioAdiciona;
	private String descripcion;
	private Integer sucursal;
	private Integer cicloEscolar;
	private Integer notaFinal;
	private int idPensumCurso;
	private Boolean eliminado;
	private int idSeccion;
	private String numeroFormulario;

	public AsignacionCurso() {
	}

	public AsignacionCurso(int idPensumCurso, int idSeccion,
			String numeroFormulario) {
		this.idPensumCurso = idPensumCurso;
		this.idSeccion = idSeccion;
		this.numeroFormulario = numeroFormulario;
	}

	public AsignacionCurso(Date fechaEliminacion, Date fechaAdicion,
			Date fechaModificacion, String usuarioElimina,
			String usuarioModifica, String usuarioAdiciona, String descripcion,
			Integer sucursal, Integer cicloEscolar, Integer notaFinal,
			int idPensumCurso, Boolean eliminado, int idSeccion,
			String numeroFormulario) {
		this.fechaEliminacion = fechaEliminacion;
		this.fechaAdicion = fechaAdicion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioElimina = usuarioElimina;
		this.usuarioModifica = usuarioModifica;
		this.usuarioAdiciona = usuarioAdiciona;
		this.descripcion = descripcion;
		this.sucursal = sucursal;
		this.cicloEscolar = cicloEscolar;
		this.notaFinal = notaFinal;
		this.idPensumCurso = idPensumCurso;
		this.eliminado = eliminado;
		this.idSeccion = idSeccion;
		this.numeroFormulario = numeroFormulario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_asignacion_curso", unique = true, nullable = false)
	public Integer getIdAsignacionCurso() {
		return this.idAsignacionCurso;
	}

	public void setIdAsignacionCurso(Integer idAsignacionCurso) {
		this.idAsignacionCurso = idAsignacionCurso;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eliminacion", length = 19)
	public Date getFechaEliminacion() {
		return this.fechaEliminacion;
	}

	public void setFechaEliminacion(Date fechaEliminacion) {
		this.fechaEliminacion = fechaEliminacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "usuario_elimina", length = 10)
	public String getUsuarioElimina() {
		return this.usuarioElimina;
	}

	public void setUsuarioElimina(String usuarioElimina) {
		this.usuarioElimina = usuarioElimina;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "ciclo_escolar")
	public Integer getCicloEscolar() {
		return this.cicloEscolar;
	}

	public void setCicloEscolar(Integer cicloEscolar) {
		this.cicloEscolar = cicloEscolar;
	}

	@Column(name = "nota_final")
	public Integer getNotaFinal() {
		return this.notaFinal;
	}

	public void setNotaFinal(Integer notaFinal) {
		this.notaFinal = notaFinal;
	}

	@Column(name = "id_pensum_curso", nullable = false)
	public int getIdPensumCurso() {
		return this.idPensumCurso;
	}

	public void setIdPensumCurso(int idPensumCurso) {
		this.idPensumCurso = idPensumCurso;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "id_seccion", nullable = false)
	public int getIdSeccion() {
		return this.idSeccion;
	}

	public void setIdSeccion(int idSeccion) {
		this.idSeccion = idSeccion;
	}

	@Column(name = "numero_formulario", nullable = false, length = 10)
	public String getNumeroFormulario() {
		return this.numeroFormulario;
	}

	public void setNumeroFormulario(String numeroFormulario) {
		this.numeroFormulario = numeroFormulario;
	}

}
