package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AsignacionPapeleria generated by hbm2java
 */
@Entity
@Table(name = "asignacion_papeleria", catalog = "academitics")
public class AsignacionPapeleria implements java.io.Serializable {

	private Integer idAsignacionPapeleria;
	private Date fechaEliminacion;
	private String usuarioElimina;
	private Date fechaAdicion;
	private Date fechaModificacion;
	private String usuarioAdiciona;
	private String usuarioModifica;
	private Integer sucursal;
	private Integer cicloEscolar;
	private Date fechaAdjunto;
	private Boolean estado;
	private Date idUsuarioAdjunta;
	private String imagen;
	private Boolean eliminado;
	private int idPapeleria;
	private String numeroFormulario;

	public AsignacionPapeleria() {
	}

	public AsignacionPapeleria(int idPapeleria, String numeroFormulario) {
		this.idPapeleria = idPapeleria;
		this.numeroFormulario = numeroFormulario;
	}

	public AsignacionPapeleria(Date fechaEliminacion, String usuarioElimina,
			Date fechaAdicion, Date fechaModificacion, String usuarioAdiciona,
			String usuarioModifica, Integer sucursal, Integer cicloEscolar,
			Date fechaAdjunto, Boolean estado, Date idUsuarioAdjunta,
			String imagen, Boolean eliminado, int idPapeleria,
			String numeroFormulario) {
		this.fechaEliminacion = fechaEliminacion;
		this.usuarioElimina = usuarioElimina;
		this.fechaAdicion = fechaAdicion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioAdiciona = usuarioAdiciona;
		this.usuarioModifica = usuarioModifica;
		this.sucursal = sucursal;
		this.cicloEscolar = cicloEscolar;
		this.fechaAdjunto = fechaAdjunto;
		this.estado = estado;
		this.idUsuarioAdjunta = idUsuarioAdjunta;
		this.imagen = imagen;
		this.eliminado = eliminado;
		this.idPapeleria = idPapeleria;
		this.numeroFormulario = numeroFormulario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_asignacion_papeleria", unique = true, nullable = false)
	public Integer getIdAsignacionPapeleria() {
		return this.idAsignacionPapeleria;
	}

	public void setIdAsignacionPapeleria(Integer idAsignacionPapeleria) {
		this.idAsignacionPapeleria = idAsignacionPapeleria;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eliminacion", length = 19)
	public Date getFechaEliminacion() {
		return this.fechaEliminacion;
	}

	public void setFechaEliminacion(Date fechaEliminacion) {
		this.fechaEliminacion = fechaEliminacion;
	}

	@Column(name = "usuario_elimina", length = 10)
	public String getUsuarioElimina() {
		return this.usuarioElimina;
	}

	public void setUsuarioElimina(String usuarioElimina) {
		this.usuarioElimina = usuarioElimina;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "ciclo_escolar")
	public Integer getCicloEscolar() {
		return this.cicloEscolar;
	}

	public void setCicloEscolar(Integer cicloEscolar) {
		this.cicloEscolar = cicloEscolar;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_adjunto", length = 10)
	public Date getFechaAdjunto() {
		return this.fechaAdjunto;
	}

	public void setFechaAdjunto(Date fechaAdjunto) {
		this.fechaAdjunto = fechaAdjunto;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "id_usuario_adjunta", length = 19)
	public Date getIdUsuarioAdjunta() {
		return this.idUsuarioAdjunta;
	}

	public void setIdUsuarioAdjunta(Date idUsuarioAdjunta) {
		this.idUsuarioAdjunta = idUsuarioAdjunta;
	}

	@Column(name = "imagen")
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "id_papeleria", nullable = false)
	public int getIdPapeleria() {
		return this.idPapeleria;
	}

	public void setIdPapeleria(int idPapeleria) {
		this.idPapeleria = idPapeleria;
	}

	@Column(name = "numero_formulario", nullable = false, length = 10)
	public String getNumeroFormulario() {
		return this.numeroFormulario;
	}

	public void setNumeroFormulario(String numeroFormulario) {
		this.numeroFormulario = numeroFormulario;
	}

}
