package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cobro generated by hbm2java
 */
@Entity
@Table(name = "cobro", catalog = "academitics")
public class Cobro implements java.io.Serializable {

	private Integer idCobro;
	private Date fechaAdicion;
	private Date fechaModificacion;
	private String usuarioAdiciona;
	private String usuarioModifica;
	private Integer sucursal;
	private String cicloEscolar;
	private String lugarPago;
	private Boolean estado;
	private String serie;
	private Integer correlativo;
	private Boolean eliminado;
	private BigDecimal total;
	private Date fecha;
	private String idAnio;
	private int idCorrelativo;
	private int idCarrera;
	private int idNivel;

	public Cobro() {
	}

	public Cobro(String idAnio, int idCorrelativo, int idCarrera, int idNivel) {
		this.idAnio = idAnio;
		this.idCorrelativo = idCorrelativo;
		this.idCarrera = idCarrera;
		this.idNivel = idNivel;
	}

	public Cobro(Date fechaAdicion, Date fechaModificacion,
			String usuarioAdiciona, String usuarioModifica, Integer sucursal,
			String cicloEscolar, String lugarPago, Boolean estado,
			String serie, Integer correlativo, Boolean eliminado,
			BigDecimal total, Date fecha, String idAnio, int idCorrelativo,
			int idCarrera, int idNivel) {
		this.fechaAdicion = fechaAdicion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioAdiciona = usuarioAdiciona;
		this.usuarioModifica = usuarioModifica;
		this.sucursal = sucursal;
		this.cicloEscolar = cicloEscolar;
		this.lugarPago = lugarPago;
		this.estado = estado;
		this.serie = serie;
		this.correlativo = correlativo;
		this.eliminado = eliminado;
		this.total = total;
		this.fecha = fecha;
		this.idAnio = idAnio;
		this.idCorrelativo = idCorrelativo;
		this.idCarrera = idCarrera;
		this.idNivel = idNivel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_cobro", unique = true, nullable = false)
	public Integer getIdCobro() {
		return this.idCobro;
	}

	public void setIdCobro(Integer idCobro) {
		this.idCobro = idCobro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "ciclo_escolar", length = 10)
	public String getCicloEscolar() {
		return this.cicloEscolar;
	}

	public void setCicloEscolar(String cicloEscolar) {
		this.cicloEscolar = cicloEscolar;
	}

	@Column(name = "lugar_pago")
	public String getLugarPago() {
		return this.lugarPago;
	}

	public void setLugarPago(String lugarPago) {
		this.lugarPago = lugarPago;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "serie", length = 25)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@Column(name = "correlativo")
	public Integer getCorrelativo() {
		return this.correlativo;
	}

	public void setCorrelativo(Integer correlativo) {
		this.correlativo = correlativo;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "total", precision = 10)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "id_anio", nullable = false, length = 2)
	public String getIdAnio() {
		return this.idAnio;
	}

	public void setIdAnio(String idAnio) {
		this.idAnio = idAnio;
	}

	@Column(name = "id_correlativo", nullable = false)
	public int getIdCorrelativo() {
		return this.idCorrelativo;
	}

	public void setIdCorrelativo(int idCorrelativo) {
		this.idCorrelativo = idCorrelativo;
	}

	@Column(name = "id_carrera", nullable = false)
	public int getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(int idCarrera) {
		this.idCarrera = idCarrera;
	}

	@Column(name = "id_nivel", nullable = false)
	public int getIdNivel() {
		return this.idNivel;
	}

	public void setIdNivel(int idNivel) {
		this.idNivel = idNivel;
	}

}
