package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConceptoCobro generated by hbm2java
 */
@Entity
@Table(name = "concepto_cobro", catalog = "academitics")
public class ConceptoCobro implements java.io.Serializable {

	private Integer idConceptoCobro;
	private Date fechaModificacion;
	private Date fechaAdicion;
	private String usuarioModifica;
	private String usuarioAdiciona;
	private Integer sucursal;
	private BigDecimal cantidad;
	private Date fechaInicioVigencia;
	private Boolean eliminado;
	private BigDecimal porcentajeMora;
	private Date fechaVencimiento;
	private String nombre;
	private String descrpcion;
	private int idTipoConceptoCobro;

	public ConceptoCobro() {
	}

	public ConceptoCobro(int idTipoConceptoCobro) {
		this.idTipoConceptoCobro = idTipoConceptoCobro;
	}

	public ConceptoCobro(Date fechaModificacion, Date fechaAdicion,
			String usuarioModifica, String usuarioAdiciona, Integer sucursal,
			BigDecimal cantidad, Date fechaInicioVigencia, Boolean eliminado,
			BigDecimal porcentajeMora, Date fechaVencimiento, String nombre,
			String descrpcion, int idTipoConceptoCobro) {
		this.fechaModificacion = fechaModificacion;
		this.fechaAdicion = fechaAdicion;
		this.usuarioModifica = usuarioModifica;
		this.usuarioAdiciona = usuarioAdiciona;
		this.sucursal = sucursal;
		this.cantidad = cantidad;
		this.fechaInicioVigencia = fechaInicioVigencia;
		this.eliminado = eliminado;
		this.porcentajeMora = porcentajeMora;
		this.fechaVencimiento = fechaVencimiento;
		this.nombre = nombre;
		this.descrpcion = descrpcion;
		this.idTipoConceptoCobro = idTipoConceptoCobro;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_concepto_cobro", unique = true, nullable = false)
	public Integer getIdConceptoCobro() {
		return this.idConceptoCobro;
	}

	public void setIdConceptoCobro(Integer idConceptoCobro) {
		this.idConceptoCobro = idConceptoCobro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "cantidad", precision = 10)
	public BigDecimal getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_inicio_vigencia", length = 19)
	public Date getFechaInicioVigencia() {
		return this.fechaInicioVigencia;
	}

	public void setFechaInicioVigencia(Date fechaInicioVigencia) {
		this.fechaInicioVigencia = fechaInicioVigencia;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "porcentaje_mora", precision = 10)
	public BigDecimal getPorcentajeMora() {
		return this.porcentajeMora;
	}

	public void setPorcentajeMora(BigDecimal porcentajeMora) {
		this.porcentajeMora = porcentajeMora;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_vencimiento", length = 19)
	public Date getFechaVencimiento() {
		return this.fechaVencimiento;
	}

	public void setFechaVencimiento(Date fechaVencimiento) {
		this.fechaVencimiento = fechaVencimiento;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descrpcion")
	public String getDescrpcion() {
		return this.descrpcion;
	}

	public void setDescrpcion(String descrpcion) {
		this.descrpcion = descrpcion;
	}

	@Column(name = "id_tipo_concepto_cobro", nullable = false)
	public int getIdTipoConceptoCobro() {
		return this.idTipoConceptoCobro;
	}

	public void setIdTipoConceptoCobro(int idTipoConceptoCobro) {
		this.idTipoConceptoCobro = idTipoConceptoCobro;
	}

}
