package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConfigTablaId generated by hbm2java
 */
@Embeddable
public class ConfigTablaId implements java.io.Serializable {

	private String tabla;
	private String nombreCampo;

	public ConfigTablaId() {
	}

	public ConfigTablaId(String tabla, String nombreCampo) {
		this.tabla = tabla;
		this.nombreCampo = nombreCampo;
	}

	@Column(name = "tabla", nullable = false, length = 100)
	public String getTabla() {
		return this.tabla;
	}

	public void setTabla(String tabla) {
		this.tabla = tabla;
	}

	@Column(name = "nombre_campo", nullable = false, length = 50)
	public String getNombreCampo() {
		return this.nombreCampo;
	}

	public void setNombreCampo(String nombreCampo) {
		this.nombreCampo = nombreCampo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConfigTablaId))
			return false;
		ConfigTablaId castOther = (ConfigTablaId) other;

		return ((this.getTabla() == castOther.getTabla()) || (this.getTabla() != null
				&& castOther.getTabla() != null && this.getTabla().equals(
				castOther.getTabla())))
				&& ((this.getNombreCampo() == castOther.getNombreCampo()) || (this
						.getNombreCampo() != null
						&& castOther.getNombreCampo() != null && this
						.getNombreCampo().equals(castOther.getNombreCampo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTabla() == null ? 0 : this.getTabla().hashCode());
		result = 37
				* result
				+ (getNombreCampo() == null ? 0 : this.getNombreCampo()
						.hashCode());
		return result;
	}

}
