package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ConfigTabla generated by hbm2java
 */
@Entity
@Table(name = "config_tabla", catalog = "academitics")
public class ConfigTabla implements java.io.Serializable {

	private ConfigTablaId id;
	private Integer orden;
	private Integer min;
	private Integer max;
	private String etiqueta;
	private String id_1;
	private String formato;
	private byte seMuestraEnTabla;
	private byte requerido;
	private String tipoValidacion;
	private int idConfigTablaMaestro;

	public ConfigTabla() {
	}

	public ConfigTabla(ConfigTablaId id, byte seMuestraEnTabla, byte requerido,
			int idConfigTablaMaestro) {
		this.id = id;
		this.seMuestraEnTabla = seMuestraEnTabla;
		this.requerido = requerido;
		this.idConfigTablaMaestro = idConfigTablaMaestro;
	}

	public ConfigTabla(ConfigTablaId id, Integer orden, Integer min,
			Integer max, String etiqueta, String id_1, String formato,
			byte seMuestraEnTabla, byte requerido, String tipoValidacion,
			int idConfigTablaMaestro) {
		this.id = id;
		this.orden = orden;
		this.min = min;
		this.max = max;
		this.etiqueta = etiqueta;
		this.id_1 = id_1;
		this.formato = formato;
		this.seMuestraEnTabla = seMuestraEnTabla;
		this.requerido = requerido;
		this.tipoValidacion = tipoValidacion;
		this.idConfigTablaMaestro = idConfigTablaMaestro;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "tabla", column = @Column(name = "tabla", nullable = false, length = 100)),
			@AttributeOverride(name = "nombreCampo", column = @Column(name = "nombre_campo", nullable = false, length = 50)) })
	public ConfigTablaId getId() {
		return this.id;
	}

	public void setId(ConfigTablaId id) {
		this.id = id;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "min")
	public Integer getMin() {
		return this.min;
	}

	public void setMin(Integer min) {
		this.min = min;
	}

	@Column(name = "max")
	public Integer getMax() {
		return this.max;
	}

	public void setMax(Integer max) {
		this.max = max;
	}

	@Column(name = "etiqueta", length = 25)
	public String getEtiqueta() {
		return this.etiqueta;
	}

	public void setEtiqueta(String etiqueta) {
		this.etiqueta = etiqueta;
	}

	@Column(name = "id", length = 100)
	public String getId_1() {
		return this.id_1;
	}

	public void setId_1(String id_1) {
		this.id_1 = id_1;
	}

	@Column(name = "formato", length = 100)
	public String getFormato() {
		return this.formato;
	}

	public void setFormato(String formato) {
		this.formato = formato;
	}

	@Column(name = "seMuestraEnTabla", nullable = false)
	public byte getSeMuestraEnTabla() {
		return this.seMuestraEnTabla;
	}

	public void setSeMuestraEnTabla(byte seMuestraEnTabla) {
		this.seMuestraEnTabla = seMuestraEnTabla;
	}

	@Column(name = "requerido", nullable = false)
	public byte getRequerido() {
		return this.requerido;
	}

	public void setRequerido(byte requerido) {
		this.requerido = requerido;
	}

	@Column(name = "tipo_validacion", length = 100)
	public String getTipoValidacion() {
		return this.tipoValidacion;
	}

	public void setTipoValidacion(String tipoValidacion) {
		this.tipoValidacion = tipoValidacion;
	}

	@Column(name = "id_config_tabla_maestro", nullable = false)
	public int getIdConfigTablaMaestro() {
		return this.idConfigTablaMaestro;
	}

	public void setIdConfigTablaMaestro(int idConfigTablaMaestro) {
		this.idConfigTablaMaestro = idConfigTablaMaestro;
	}

}
