package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DetalleCobro generated by hbm2java
 */
@Entity
@Table(name = "detalle_cobro", catalog = "academitics")
public class DetalleCobro implements java.io.Serializable {

	private Integer idDetalleCobro;
	private Date fechaModificacion;
	private Date fechaAdicion;
	private String usuarioAdicion;
	private String usuarioModifica;
	private Integer sucursal;
	private String estado;
	private Boolean completo;
	private Integer idPertenece;
	private Boolean elminado;
	private String concepto;
	private BigDecimal monto;
	private int idCobro;
	private int idConceptoCobro;
	private String numeroFormulario;

	public DetalleCobro() {
	}

	public DetalleCobro(int idCobro, int idConceptoCobro,
			String numeroFormulario) {
		this.idCobro = idCobro;
		this.idConceptoCobro = idConceptoCobro;
		this.numeroFormulario = numeroFormulario;
	}

	public DetalleCobro(Date fechaModificacion, Date fechaAdicion,
			String usuarioAdicion, String usuarioModifica, Integer sucursal,
			String estado, Boolean completo, Integer idPertenece,
			Boolean elminado, String concepto, BigDecimal monto, int idCobro,
			int idConceptoCobro, String numeroFormulario) {
		this.fechaModificacion = fechaModificacion;
		this.fechaAdicion = fechaAdicion;
		this.usuarioAdicion = usuarioAdicion;
		this.usuarioModifica = usuarioModifica;
		this.sucursal = sucursal;
		this.estado = estado;
		this.completo = completo;
		this.idPertenece = idPertenece;
		this.elminado = elminado;
		this.concepto = concepto;
		this.monto = monto;
		this.idCobro = idCobro;
		this.idConceptoCobro = idConceptoCobro;
		this.numeroFormulario = numeroFormulario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_detalle_cobro", unique = true, nullable = false)
	public Integer getIdDetalleCobro() {
		return this.idDetalleCobro;
	}

	public void setIdDetalleCobro(Integer idDetalleCobro) {
		this.idDetalleCobro = idDetalleCobro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Column(name = "usuario_adicion", length = 10)
	public String getUsuarioAdicion() {
		return this.usuarioAdicion;
	}

	public void setUsuarioAdicion(String usuarioAdicion) {
		this.usuarioAdicion = usuarioAdicion;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "estado", length = 50)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "completo")
	public Boolean getCompleto() {
		return this.completo;
	}

	public void setCompleto(Boolean completo) {
		this.completo = completo;
	}

	@Column(name = "id_pertenece")
	public Integer getIdPertenece() {
		return this.idPertenece;
	}

	public void setIdPertenece(Integer idPertenece) {
		this.idPertenece = idPertenece;
	}

	@Column(name = "elminado")
	public Boolean getElminado() {
		return this.elminado;
	}

	public void setElminado(Boolean elminado) {
		this.elminado = elminado;
	}

	@Column(name = "concepto")
	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	@Column(name = "monto", precision = 10)
	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	@Column(name = "id_cobro", nullable = false)
	public int getIdCobro() {
		return this.idCobro;
	}

	public void setIdCobro(int idCobro) {
		this.idCobro = idCobro;
	}

	@Column(name = "id_concepto_cobro", nullable = false)
	public int getIdConceptoCobro() {
		return this.idConceptoCobro;
	}

	public void setIdConceptoCobro(int idConceptoCobro) {
		this.idConceptoCobro = idConceptoCobro;
	}

	@Column(name = "numero_formulario", nullable = false, length = 10)
	public String getNumeroFormulario() {
		return this.numeroFormulario;
	}

	public void setNumeroFormulario(String numeroFormulario) {
		this.numeroFormulario = numeroFormulario;
	}

}
