package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EstadoPapeleria generated by hbm2java
 */
@Entity
@Table(name = "estado_papeleria", catalog = "academitics")
public class EstadoPapeleria implements java.io.Serializable {

	private String idEstadoPapeleria;
	private Integer sucursal;
	private Boolean eliminado;
	private Date fechaModificacion;
	private Date fechaAdicion;
	private Date fechaEliminacion;
	private String usuarioAdiciona;
	private String usuarioModifica;
	private String usuarioElimina;
	private String estado;
	private String fechaCambioEstado;
	private String concepto;
	private int idAsignacionPapeleria;

	public EstadoPapeleria() {
	}

	public EstadoPapeleria(String idEstadoPapeleria, int idAsignacionPapeleria) {
		this.idEstadoPapeleria = idEstadoPapeleria;
		this.idAsignacionPapeleria = idAsignacionPapeleria;
	}

	public EstadoPapeleria(String idEstadoPapeleria, Integer sucursal,
			Boolean eliminado, Date fechaModificacion, Date fechaAdicion,
			Date fechaEliminacion, String usuarioAdiciona,
			String usuarioModifica, String usuarioElimina, String estado,
			String fechaCambioEstado, String concepto, int idAsignacionPapeleria) {
		this.idEstadoPapeleria = idEstadoPapeleria;
		this.sucursal = sucursal;
		this.eliminado = eliminado;
		this.fechaModificacion = fechaModificacion;
		this.fechaAdicion = fechaAdicion;
		this.fechaEliminacion = fechaEliminacion;
		this.usuarioAdiciona = usuarioAdiciona;
		this.usuarioModifica = usuarioModifica;
		this.usuarioElimina = usuarioElimina;
		this.estado = estado;
		this.fechaCambioEstado = fechaCambioEstado;
		this.concepto = concepto;
		this.idAsignacionPapeleria = idAsignacionPapeleria;
	}

	@Id
	@Column(name = "id_estado_papeleria", unique = true, nullable = false, length = 10)
	public String getIdEstadoPapeleria() {
		return this.idEstadoPapeleria;
	}

	public void setIdEstadoPapeleria(String idEstadoPapeleria) {
		this.idEstadoPapeleria = idEstadoPapeleria;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eliminacion", length = 19)
	public Date getFechaEliminacion() {
		return this.fechaEliminacion;
	}

	public void setFechaEliminacion(Date fechaEliminacion) {
		this.fechaEliminacion = fechaEliminacion;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Column(name = "usuario_elimina", length = 10)
	public String getUsuarioElimina() {
		return this.usuarioElimina;
	}

	public void setUsuarioElimina(String usuarioElimina) {
		this.usuarioElimina = usuarioElimina;
	}

	@Column(name = "estado", length = 10)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "fecha_cambio_estado", length = 10)
	public String getFechaCambioEstado() {
		return this.fechaCambioEstado;
	}

	public void setFechaCambioEstado(String fechaCambioEstado) {
		this.fechaCambioEstado = fechaCambioEstado;
	}

	@Column(name = "concepto", length = 10)
	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	@Column(name = "id_asignacion_papeleria", nullable = false)
	public int getIdAsignacionPapeleria() {
		return this.idAsignacionPapeleria;
	}

	public void setIdAsignacionPapeleria(int idAsignacionPapeleria) {
		this.idAsignacionPapeleria = idAsignacionPapeleria;
	}

}
