package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HistorialPeriodoId generated by hbm2java
 */
@Embeddable
public class HistorialPeriodoId implements java.io.Serializable {

	private String idHistorialPeriodo;
	private int idCobro;
	private String idHistorial;

	public HistorialPeriodoId() {
	}

	public HistorialPeriodoId(String idHistorialPeriodo, int idCobro,
			String idHistorial) {
		this.idHistorialPeriodo = idHistorialPeriodo;
		this.idCobro = idCobro;
		this.idHistorial = idHistorial;
	}

	@Column(name = "id_historial_periodo", nullable = false, length = 10)
	public String getIdHistorialPeriodo() {
		return this.idHistorialPeriodo;
	}

	public void setIdHistorialPeriodo(String idHistorialPeriodo) {
		this.idHistorialPeriodo = idHistorialPeriodo;
	}

	@Column(name = "id_cobro", nullable = false)
	public int getIdCobro() {
		return this.idCobro;
	}

	public void setIdCobro(int idCobro) {
		this.idCobro = idCobro;
	}

	@Column(name = "id_historial", nullable = false, length = 10)
	public String getIdHistorial() {
		return this.idHistorial;
	}

	public void setIdHistorial(String idHistorial) {
		this.idHistorial = idHistorial;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HistorialPeriodoId))
			return false;
		HistorialPeriodoId castOther = (HistorialPeriodoId) other;

		return ((this.getIdHistorialPeriodo() == castOther
				.getIdHistorialPeriodo()) || (this.getIdHistorialPeriodo() != null
				&& castOther.getIdHistorialPeriodo() != null && this
				.getIdHistorialPeriodo().equals(
						castOther.getIdHistorialPeriodo())))
				&& (this.getIdCobro() == castOther.getIdCobro())
				&& ((this.getIdHistorial() == castOther.getIdHistorial()) || (this
						.getIdHistorial() != null
						&& castOther.getIdHistorial() != null && this
						.getIdHistorial().equals(castOther.getIdHistorial())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdHistorialPeriodo() == null ? 0 : this
						.getIdHistorialPeriodo().hashCode());
		result = 37 * result + this.getIdCobro();
		result = 37
				* result
				+ (getIdHistorial() == null ? 0 : this.getIdHistorial()
						.hashCode());
		return result;
	}

}
