package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistorialAlumno generated by hbm2java
 */
@Entity
@Table(name = "historial_alumno", catalog = "academitics")
public class HistorialAlumno implements java.io.Serializable {

	private Integer idHistorial;
	private Integer sucursal;
	private String cicloEscolar;
	private Boolean eliminado;
	private Integer idDetalle;
	private String detalle;
	private Date fecha;
	private int idConcepto;
	private String idAnio;
	private int idCorrelativo;
	private int idAlerta;
	private int idCarrera;
	private int idNivel;

	public HistorialAlumno() {
	}

	public HistorialAlumno(int idConcepto, String idAnio, int idCorrelativo,
			int idAlerta, int idCarrera, int idNivel) {
		this.idConcepto = idConcepto;
		this.idAnio = idAnio;
		this.idCorrelativo = idCorrelativo;
		this.idAlerta = idAlerta;
		this.idCarrera = idCarrera;
		this.idNivel = idNivel;
	}

	public HistorialAlumno(Integer sucursal, String cicloEscolar,
			Boolean eliminado, Integer idDetalle, String detalle, Date fecha,
			int idConcepto, String idAnio, int idCorrelativo, int idAlerta,
			int idCarrera, int idNivel) {
		this.sucursal = sucursal;
		this.cicloEscolar = cicloEscolar;
		this.eliminado = eliminado;
		this.idDetalle = idDetalle;
		this.detalle = detalle;
		this.fecha = fecha;
		this.idConcepto = idConcepto;
		this.idAnio = idAnio;
		this.idCorrelativo = idCorrelativo;
		this.idAlerta = idAlerta;
		this.idCarrera = idCarrera;
		this.idNivel = idNivel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_historial", unique = true, nullable = false)
	public Integer getIdHistorial() {
		return this.idHistorial;
	}

	public void setIdHistorial(Integer idHistorial) {
		this.idHistorial = idHistorial;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "ciclo_escolar", length = 10)
	public String getCicloEscolar() {
		return this.cicloEscolar;
	}

	public void setCicloEscolar(String cicloEscolar) {
		this.cicloEscolar = cicloEscolar;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "id_detalle")
	public Integer getIdDetalle() {
		return this.idDetalle;
	}

	public void setIdDetalle(Integer idDetalle) {
		this.idDetalle = idDetalle;
	}

	@Column(name = "detalle")
	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "id_concepto", nullable = false)
	public int getIdConcepto() {
		return this.idConcepto;
	}

	public void setIdConcepto(int idConcepto) {
		this.idConcepto = idConcepto;
	}

	@Column(name = "id_anio", nullable = false, length = 2)
	public String getIdAnio() {
		return this.idAnio;
	}

	public void setIdAnio(String idAnio) {
		this.idAnio = idAnio;
	}

	@Column(name = "id_correlativo", nullable = false)
	public int getIdCorrelativo() {
		return this.idCorrelativo;
	}

	public void setIdCorrelativo(int idCorrelativo) {
		this.idCorrelativo = idCorrelativo;
	}

	@Column(name = "id_alerta", nullable = false)
	public int getIdAlerta() {
		return this.idAlerta;
	}

	public void setIdAlerta(int idAlerta) {
		this.idAlerta = idAlerta;
	}

	@Column(name = "id_carrera", nullable = false)
	public int getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(int idCarrera) {
		this.idCarrera = idCarrera;
	}

	@Column(name = "id_nivel", nullable = false)
	public int getIdNivel() {
		return this.idNivel;
	}

	public void setIdNivel(int idNivel) {
		this.idNivel = idNivel;
	}

}
