package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historial generated by hbm2java
 */
@Entity
@Table(name = "historial", catalog = "academitics")
public class Historial implements java.io.Serializable {

	private String idHistorial;
	private Integer sucursal;
	private Date horaInicioDia;
	private Date horaFinDia;
	private Date fecha;
	private Integer idUsuario;
	private BigDecimal cantidadEntregada;
	private String observaciones;

	public Historial() {
	}

	public Historial(String idHistorial) {
		this.idHistorial = idHistorial;
	}

	public Historial(String idHistorial, Integer sucursal, Date horaInicioDia,
			Date horaFinDia, Date fecha, Integer idUsuario,
			BigDecimal cantidadEntregada, String observaciones) {
		this.idHistorial = idHistorial;
		this.sucursal = sucursal;
		this.horaInicioDia = horaInicioDia;
		this.horaFinDia = horaFinDia;
		this.fecha = fecha;
		this.idUsuario = idUsuario;
		this.cantidadEntregada = cantidadEntregada;
		this.observaciones = observaciones;
	}

	@Id
	@Column(name = "id_historial", unique = true, nullable = false, length = 10)
	public String getIdHistorial() {
		return this.idHistorial;
	}

	public void setIdHistorial(String idHistorial) {
		this.idHistorial = idHistorial;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_inicio_dia", length = 8)
	public Date getHoraInicioDia() {
		return this.horaInicioDia;
	}

	public void setHoraInicioDia(Date horaInicioDia) {
		this.horaInicioDia = horaInicioDia;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_fin_dia", length = 8)
	public Date getHoraFinDia() {
		return this.horaFinDia;
	}

	public void setHoraFinDia(Date horaFinDia) {
		this.horaFinDia = horaFinDia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "id_usuario")
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "cantidad_entregada", precision = 10)
	public BigDecimal getCantidadEntregada() {
		return this.cantidadEntregada;
	}

	public void setCantidadEntregada(BigDecimal cantidadEntregada) {
		this.cantidadEntregada = cantidadEntregada;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
