package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * HistorialPeriodo generated by hbm2java
 */
@Entity
@Table(name = "historial_periodo", catalog = "academitics")
public class HistorialPeriodo implements java.io.Serializable {

	private HistorialPeriodoId id;
	private Integer sucursal;

	public HistorialPeriodo() {
	}

	public HistorialPeriodo(HistorialPeriodoId id) {
		this.id = id;
	}

	public HistorialPeriodo(HistorialPeriodoId id, Integer sucursal) {
		this.id = id;
		this.sucursal = sucursal;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idHistorialPeriodo", column = @Column(name = "id_historial_periodo", nullable = false, length = 10)),
			@AttributeOverride(name = "idCobro", column = @Column(name = "id_cobro", nullable = false)),
			@AttributeOverride(name = "idHistorial", column = @Column(name = "id_historial", nullable = false, length = 10)) })
	public HistorialPeriodoId getId() {
		return this.id;
	}

	public void setId(HistorialPeriodoId id) {
		this.id = id;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

}
