package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name = "horario", catalog = "academitics")
public class Horario implements java.io.Serializable {

	private String idHorario;
	private Date fechaEliminacion;
	private Date fechaModificacion;
	private Date fechaAdicion;
	private String usuarioAdiciona;
	private String usuarioModifica;
	private String usuarioElimina;
	private Integer sucursal;
	private Boolean eliminado;
	private String nombre;
	private int idNivel;
	private int idJornada;

	public Horario() {
	}

	public Horario(String idHorario, int idNivel, int idJornada) {
		this.idHorario = idHorario;
		this.idNivel = idNivel;
		this.idJornada = idJornada;
	}

	public Horario(String idHorario, Date fechaEliminacion,
			Date fechaModificacion, Date fechaAdicion, String usuarioAdiciona,
			String usuarioModifica, String usuarioElimina, Integer sucursal,
			Boolean eliminado, String nombre, int idNivel, int idJornada) {
		this.idHorario = idHorario;
		this.fechaEliminacion = fechaEliminacion;
		this.fechaModificacion = fechaModificacion;
		this.fechaAdicion = fechaAdicion;
		this.usuarioAdiciona = usuarioAdiciona;
		this.usuarioModifica = usuarioModifica;
		this.usuarioElimina = usuarioElimina;
		this.sucursal = sucursal;
		this.eliminado = eliminado;
		this.nombre = nombre;
		this.idNivel = idNivel;
		this.idJornada = idJornada;
	}

	@Id
	@Column(name = "id_horario", unique = true, nullable = false, length = 10)
	public String getIdHorario() {
		return this.idHorario;
	}

	public void setIdHorario(String idHorario) {
		this.idHorario = idHorario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eliminacion", length = 19)
	public Date getFechaEliminacion() {
		return this.fechaEliminacion;
	}

	public void setFechaEliminacion(Date fechaEliminacion) {
		this.fechaEliminacion = fechaEliminacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Column(name = "usuario_elimina", length = 10)
	public String getUsuarioElimina() {
		return this.usuarioElimina;
	}

	public void setUsuarioElimina(String usuarioElimina) {
		this.usuarioElimina = usuarioElimina;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "nombre", length = 10)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "id_nivel", nullable = false)
	public int getIdNivel() {
		return this.idNivel;
	}

	public void setIdNivel(int idNivel) {
		this.idNivel = idNivel;
	}

	@Column(name = "id_jornada", nullable = false)
	public int getIdJornada() {
		return this.idJornada;
	}

	public void setIdJornada(int idJornada) {
		this.idJornada = idJornada;
	}

}
