package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HorarioDetalle generated by hbm2java
 */
@Entity
@Table(name = "horario_detalle", catalog = "academitics")
public class HorarioDetalle implements java.io.Serializable {

	private Integer idDetallleHorario;
	private Date fechaEliminacion;
	private String usuarioElimina;
	private Date fechaModificacion;
	private Date fechaAdicion;
	private String usuarioAdiciona;
	private String usuarioModifica;
	private String sucursal;
	private Boolean eliminado;
	private Byte estado;
	private Date horaInicio;
	private Date horaFin;
	private String idHorario;

	public HorarioDetalle() {
	}

	public HorarioDetalle(String idHorario) {
		this.idHorario = idHorario;
	}

	public HorarioDetalle(Date fechaEliminacion, String usuarioElimina,
			Date fechaModificacion, Date fechaAdicion, String usuarioAdiciona,
			String usuarioModifica, String sucursal, Boolean eliminado,
			Byte estado, Date horaInicio, Date horaFin, String idHorario) {
		this.fechaEliminacion = fechaEliminacion;
		this.usuarioElimina = usuarioElimina;
		this.fechaModificacion = fechaModificacion;
		this.fechaAdicion = fechaAdicion;
		this.usuarioAdiciona = usuarioAdiciona;
		this.usuarioModifica = usuarioModifica;
		this.sucursal = sucursal;
		this.eliminado = eliminado;
		this.estado = estado;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.idHorario = idHorario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_detallle_horario", unique = true, nullable = false)
	public Integer getIdDetallleHorario() {
		return this.idDetallleHorario;
	}

	public void setIdDetallleHorario(Integer idDetallleHorario) {
		this.idDetallleHorario = idDetallleHorario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eliminacion", length = 19)
	public Date getFechaEliminacion() {
		return this.fechaEliminacion;
	}

	public void setFechaEliminacion(Date fechaEliminacion) {
		this.fechaEliminacion = fechaEliminacion;
	}

	@Column(name = "usuario_elimina", length = 10)
	public String getUsuarioElimina() {
		return this.usuarioElimina;
	}

	public void setUsuarioElimina(String usuarioElimina) {
		this.usuarioElimina = usuarioElimina;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Column(name = "sucursal", length = 10)
	public String getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(String sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "estado")
	public Byte getEstado() {
		return this.estado;
	}

	public void setEstado(Byte estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_inicio", length = 19)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_fin", length = 19)
	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	@Column(name = "id_horario", nullable = false, length = 10)
	public String getIdHorario() {
		return this.idHorario;
	}

	public void setIdHorario(String idHorario) {
		this.idHorario = idHorario;
	}

}
