package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IdiomasAlumno generated by hbm2java
 */
@Entity
@Table(name = "idiomas_alumno", catalog = "academitics")
public class IdiomasAlumno implements java.io.Serializable {

	private IdiomasAlumnoId id;
	private Date fechaEliminacion;
	private Date fechaModificacion;
	private Date fechaAdicion;
	private String usuarioModifica;
	private String usuarioElimina;
	private String usuarioAdiciona;
	private Boolean idiomaMaterno;
	private Boolean eliminado;
	private Integer sucursal;
	private String idAnio;
	private int idCorrelativo;
	private int idCarrera;
	private int idCompresionIdioma;
	private int idNivel;

	public IdiomasAlumno() {
	}

	public IdiomasAlumno(IdiomasAlumnoId id, String idAnio, int idCorrelativo,
			int idCarrera, int idCompresionIdioma, int idNivel) {
		this.id = id;
		this.idAnio = idAnio;
		this.idCorrelativo = idCorrelativo;
		this.idCarrera = idCarrera;
		this.idCompresionIdioma = idCompresionIdioma;
		this.idNivel = idNivel;
	}

	public IdiomasAlumno(IdiomasAlumnoId id, Date fechaEliminacion,
			Date fechaModificacion, Date fechaAdicion, String usuarioModifica,
			String usuarioElimina, String usuarioAdiciona,
			Boolean idiomaMaterno, Boolean eliminado, Integer sucursal,
			String idAnio, int idCorrelativo, int idCarrera,
			int idCompresionIdioma, int idNivel) {
		this.id = id;
		this.fechaEliminacion = fechaEliminacion;
		this.fechaModificacion = fechaModificacion;
		this.fechaAdicion = fechaAdicion;
		this.usuarioModifica = usuarioModifica;
		this.usuarioElimina = usuarioElimina;
		this.usuarioAdiciona = usuarioAdiciona;
		this.idiomaMaterno = idiomaMaterno;
		this.eliminado = eliminado;
		this.sucursal = sucursal;
		this.idAnio = idAnio;
		this.idCorrelativo = idCorrelativo;
		this.idCarrera = idCarrera;
		this.idCompresionIdioma = idCompresionIdioma;
		this.idNivel = idNivel;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idIdiomasAlumno", column = @Column(name = "id_idiomas_alumno", nullable = false, length = 10)),
			@AttributeOverride(name = "idIdioma", column = @Column(name = "id_idioma", nullable = false)) })
	public IdiomasAlumnoId getId() {
		return this.id;
	}

	public void setId(IdiomasAlumnoId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eliminacion", length = 19)
	public Date getFechaEliminacion() {
		return this.fechaEliminacion;
	}

	public void setFechaEliminacion(Date fechaEliminacion) {
		this.fechaEliminacion = fechaEliminacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_modificacion", length = 10)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Column(name = "usuario_elimina", length = 10)
	public String getUsuarioElimina() {
		return this.usuarioElimina;
	}

	public void setUsuarioElimina(String usuarioElimina) {
		this.usuarioElimina = usuarioElimina;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Column(name = "idioma_materno")
	public Boolean getIdiomaMaterno() {
		return this.idiomaMaterno;
	}

	public void setIdiomaMaterno(Boolean idiomaMaterno) {
		this.idiomaMaterno = idiomaMaterno;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "id_anio", nullable = false, length = 2)
	public String getIdAnio() {
		return this.idAnio;
	}

	public void setIdAnio(String idAnio) {
		this.idAnio = idAnio;
	}

	@Column(name = "id_correlativo", nullable = false)
	public int getIdCorrelativo() {
		return this.idCorrelativo;
	}

	public void setIdCorrelativo(int idCorrelativo) {
		this.idCorrelativo = idCorrelativo;
	}

	@Column(name = "id_carrera", nullable = false)
	public int getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(int idCarrera) {
		this.idCarrera = idCarrera;
	}

	@Column(name = "id_compresion_idioma", nullable = false)
	public int getIdCompresionIdioma() {
		return this.idCompresionIdioma;
	}

	public void setIdCompresionIdioma(int idCompresionIdioma) {
		this.idCompresionIdioma = idCompresionIdioma;
	}

	@Column(name = "id_nivel", nullable = false)
	public int getIdNivel() {
		return this.idNivel;
	}

	public void setIdNivel(int idNivel) {
		this.idNivel = idNivel;
	}

}
