package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IdiomasAlumnoId generated by hbm2java
 */
@Embeddable
public class IdiomasAlumnoId implements java.io.Serializable {

	private String idIdiomasAlumno;
	private int idIdioma;

	public IdiomasAlumnoId() {
	}

	public IdiomasAlumnoId(String idIdiomasAlumno, int idIdioma) {
		this.idIdiomasAlumno = idIdiomasAlumno;
		this.idIdioma = idIdioma;
	}

	@Column(name = "id_idiomas_alumno", nullable = false, length = 10)
	public String getIdIdiomasAlumno() {
		return this.idIdiomasAlumno;
	}

	public void setIdIdiomasAlumno(String idIdiomasAlumno) {
		this.idIdiomasAlumno = idIdiomasAlumno;
	}

	@Column(name = "id_idioma", nullable = false)
	public int getIdIdioma() {
		return this.idIdioma;
	}

	public void setIdIdioma(int idIdioma) {
		this.idIdioma = idIdioma;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IdiomasAlumnoId))
			return false;
		IdiomasAlumnoId castOther = (IdiomasAlumnoId) other;

		return ((this.getIdIdiomasAlumno() == castOther.getIdIdiomasAlumno()) || (this
				.getIdIdiomasAlumno() != null
				&& castOther.getIdIdiomasAlumno() != null && this
				.getIdIdiomasAlumno().equals(castOther.getIdIdiomasAlumno())))
				&& (this.getIdIdioma() == castOther.getIdIdioma());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdIdiomasAlumno() == null ? 0 : this.getIdIdiomasAlumno()
						.hashCode());
		result = 37 * result + this.getIdIdioma();
		return result;
	}

}
