package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inscripcion generated by hbm2java
 */
@Entity
@Table(name = "inscripcion", catalog = "academitics")
public class Inscripcion implements java.io.Serializable {

	private String numeroFormulario;
	private String numeroAcceso;
	private String usuarioElimina;
	private Date fechaEliminacion;
	private String usuarioAdiciona;
	private String usuarioModifica;
	private Date fechaAdicion;
	private String fechaModificacion;
	private Integer sucursal;
	private Integer cicloEscolar;
	private String idContrato;
	private String contratoPath;
	private Boolean estado;
	private Date fecha;
	private String idAnio;
	private Boolean elminado;
	private int idCorrelativo;
	private int idCarrera;
	private int idCiclo;
	private int idNivel;
	private int idJornada;

	public Inscripcion() {
	}

	public Inscripcion(String numeroFormulario, String numeroAcceso,
			String idAnio, int idCorrelativo, int idCarrera, int idCiclo,
			int idNivel, int idJornada) {
		this.numeroFormulario = numeroFormulario;
		this.numeroAcceso = numeroAcceso;
		this.idAnio = idAnio;
		this.idCorrelativo = idCorrelativo;
		this.idCarrera = idCarrera;
		this.idCiclo = idCiclo;
		this.idNivel = idNivel;
		this.idJornada = idJornada;
	}

	public Inscripcion(String numeroFormulario, String numeroAcceso,
			String usuarioElimina, Date fechaEliminacion,
			String usuarioAdiciona, String usuarioModifica, Date fechaAdicion,
			String fechaModificacion, Integer sucursal, Integer cicloEscolar,
			String idContrato, String contratoPath, Boolean estado, Date fecha,
			String idAnio, Boolean elminado, int idCorrelativo, int idCarrera,
			int idCiclo, int idNivel, int idJornada) {
		this.numeroFormulario = numeroFormulario;
		this.numeroAcceso = numeroAcceso;
		this.usuarioElimina = usuarioElimina;
		this.fechaEliminacion = fechaEliminacion;
		this.usuarioAdiciona = usuarioAdiciona;
		this.usuarioModifica = usuarioModifica;
		this.fechaAdicion = fechaAdicion;
		this.fechaModificacion = fechaModificacion;
		this.sucursal = sucursal;
		this.cicloEscolar = cicloEscolar;
		this.idContrato = idContrato;
		this.contratoPath = contratoPath;
		this.estado = estado;
		this.fecha = fecha;
		this.idAnio = idAnio;
		this.elminado = elminado;
		this.idCorrelativo = idCorrelativo;
		this.idCarrera = idCarrera;
		this.idCiclo = idCiclo;
		this.idNivel = idNivel;
		this.idJornada = idJornada;
	}

	@Id
	@Column(name = "numero_formulario", unique = true, nullable = false, length = 10)
	public String getNumeroFormulario() {
		return this.numeroFormulario;
	}

	public void setNumeroFormulario(String numeroFormulario) {
		this.numeroFormulario = numeroFormulario;
	}

	@Column(name = "numero_acceso", nullable = false, length = 10)
	public String getNumeroAcceso() {
		return this.numeroAcceso;
	}

	public void setNumeroAcceso(String numeroAcceso) {
		this.numeroAcceso = numeroAcceso;
	}

	@Column(name = "usuario_elimina", length = 10)
	public String getUsuarioElimina() {
		return this.usuarioElimina;
	}

	public void setUsuarioElimina(String usuarioElimina) {
		this.usuarioElimina = usuarioElimina;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eliminacion", length = 19)
	public Date getFechaEliminacion() {
		return this.fechaEliminacion;
	}

	public void setFechaEliminacion(Date fechaEliminacion) {
		this.fechaEliminacion = fechaEliminacion;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Column(name = "fecha_modificacion", length = 10)
	public String getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(String fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "ciclo_escolar")
	public Integer getCicloEscolar() {
		return this.cicloEscolar;
	}

	public void setCicloEscolar(Integer cicloEscolar) {
		this.cicloEscolar = cicloEscolar;
	}

	@Column(name = "id_contrato", length = 50)
	public String getIdContrato() {
		return this.idContrato;
	}

	public void setIdContrato(String idContrato) {
		this.idContrato = idContrato;
	}

	@Column(name = "contrato_path")
	public String getContratoPath() {
		return this.contratoPath;
	}

	public void setContratoPath(String contratoPath) {
		this.contratoPath = contratoPath;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "id_anio", nullable = false, length = 2)
	public String getIdAnio() {
		return this.idAnio;
	}

	public void setIdAnio(String idAnio) {
		this.idAnio = idAnio;
	}

	@Column(name = "elminado")
	public Boolean getElminado() {
		return this.elminado;
	}

	public void setElminado(Boolean elminado) {
		this.elminado = elminado;
	}

	@Column(name = "id_correlativo", nullable = false)
	public int getIdCorrelativo() {
		return this.idCorrelativo;
	}

	public void setIdCorrelativo(int idCorrelativo) {
		this.idCorrelativo = idCorrelativo;
	}

	@Column(name = "id_carrera", nullable = false)
	public int getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(int idCarrera) {
		this.idCarrera = idCarrera;
	}

	@Column(name = "id_ciclo", nullable = false)
	public int getIdCiclo() {
		return this.idCiclo;
	}

	public void setIdCiclo(int idCiclo) {
		this.idCiclo = idCiclo;
	}

	@Column(name = "id_nivel", nullable = false)
	public int getIdNivel() {
		return this.idNivel;
	}

	public void setIdNivel(int idNivel) {
		this.idNivel = idNivel;
	}

	@Column(name = "id_jornada", nullable = false)
	public int getIdJornada() {
		return this.idJornada;
	}

	public void setIdJornada(int idJornada) {
		this.idJornada = idJornada;
	}

}
