package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MunicipioId generated by hbm2java
 */
@Embeddable
public class MunicipioId implements java.io.Serializable {

	private int idMunicipio;
	private int idDepartamento;

	public MunicipioId() {
	}

	public MunicipioId(int idMunicipio, int idDepartamento) {
		this.idMunicipio = idMunicipio;
		this.idDepartamento = idDepartamento;
	}

	@Column(name = "id_municipio", nullable = false)
	public int getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(int idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	@Column(name = "id_departamento", nullable = false)
	public int getIdDepartamento() {
		return this.idDepartamento;
	}

	public void setIdDepartamento(int idDepartamento) {
		this.idDepartamento = idDepartamento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MunicipioId))
			return false;
		MunicipioId castOther = (MunicipioId) other;

		return (this.getIdMunicipio() == castOther.getIdMunicipio())
				&& (this.getIdDepartamento() == castOther.getIdDepartamento());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMunicipio();
		result = 37 * result + this.getIdDepartamento();
		return result;
	}

}
