package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Papeleria generated by hbm2java
 */
@Entity
@Table(name = "papeleria", catalog = "academitics")
public class Papeleria implements java.io.Serializable {

	private Integer idPapeleria;
	private String usuarioEliminacion;
	private Date fechaEliminacion;
	private String usuarioAdiciona;
	private String usuarioModifica;
	private Date fechaAdicion;
	private Date fechaModificacion;
	private Integer sucursal;
	private Boolean eliminado;
	private Boolean estado;
	private String nombre;
	private int idTipoPapeleria;

	public Papeleria() {
	}

	public Papeleria(int idTipoPapeleria) {
		this.idTipoPapeleria = idTipoPapeleria;
	}

	public Papeleria(String usuarioEliminacion, Date fechaEliminacion,
			String usuarioAdiciona, String usuarioModifica, Date fechaAdicion,
			Date fechaModificacion, Integer sucursal, Boolean eliminado,
			Boolean estado, String nombre, int idTipoPapeleria) {
		this.usuarioEliminacion = usuarioEliminacion;
		this.fechaEliminacion = fechaEliminacion;
		this.usuarioAdiciona = usuarioAdiciona;
		this.usuarioModifica = usuarioModifica;
		this.fechaAdicion = fechaAdicion;
		this.fechaModificacion = fechaModificacion;
		this.sucursal = sucursal;
		this.eliminado = eliminado;
		this.estado = estado;
		this.nombre = nombre;
		this.idTipoPapeleria = idTipoPapeleria;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_papeleria", unique = true, nullable = false)
	public Integer getIdPapeleria() {
		return this.idPapeleria;
	}

	public void setIdPapeleria(Integer idPapeleria) {
		this.idPapeleria = idPapeleria;
	}

	@Column(name = "usuario_eliminacion", length = 10)
	public String getUsuarioEliminacion() {
		return this.usuarioEliminacion;
	}

	public void setUsuarioEliminacion(String usuarioEliminacion) {
		this.usuarioEliminacion = usuarioEliminacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eliminacion", length = 19)
	public Date getFechaEliminacion() {
		return this.fechaEliminacion;
	}

	public void setFechaEliminacion(Date fechaEliminacion) {
		this.fechaEliminacion = fechaEliminacion;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "id_tipo_papeleria", nullable = false)
	public int getIdTipoPapeleria() {
		return this.idTipoPapeleria;
	}

	public void setIdTipoPapeleria(int idTipoPapeleria) {
		this.idTipoPapeleria = idTipoPapeleria;
	}

}
