package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PensumCurso generated by hbm2java
 */
@Entity
@Table(name = "pensum_curso", catalog = "academitics")
public class PensumCurso implements java.io.Serializable {

	private Integer idPensumCurso;
	private Date fechaEliminacion;
	private Date fechaModificacion;
	private String fechaAdicion;
	private String usuarioModifica;
	private String usuarioElimina;
	private String usuarioAdiciona;
	private Integer sucursal;
	private Integer cicloEscolar;
	private Boolean eliminado;
	private int idCurso;
	private int idPensum;

	public PensumCurso() {
	}

	public PensumCurso(int idCurso, int idPensum) {
		this.idCurso = idCurso;
		this.idPensum = idPensum;
	}

	public PensumCurso(Date fechaEliminacion, Date fechaModificacion,
			String fechaAdicion, String usuarioModifica, String usuarioElimina,
			String usuarioAdiciona, Integer sucursal, Integer cicloEscolar,
			Boolean eliminado, int idCurso, int idPensum) {
		this.fechaEliminacion = fechaEliminacion;
		this.fechaModificacion = fechaModificacion;
		this.fechaAdicion = fechaAdicion;
		this.usuarioModifica = usuarioModifica;
		this.usuarioElimina = usuarioElimina;
		this.usuarioAdiciona = usuarioAdiciona;
		this.sucursal = sucursal;
		this.cicloEscolar = cicloEscolar;
		this.eliminado = eliminado;
		this.idCurso = idCurso;
		this.idPensum = idPensum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_pensum_curso", unique = true, nullable = false)
	public Integer getIdPensumCurso() {
		return this.idPensumCurso;
	}

	public void setIdPensumCurso(Integer idPensumCurso) {
		this.idPensumCurso = idPensumCurso;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eliminacion", length = 19)
	public Date getFechaEliminacion() {
		return this.fechaEliminacion;
	}

	public void setFechaEliminacion(Date fechaEliminacion) {
		this.fechaEliminacion = fechaEliminacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "fecha_adicion", length = 10)
	public String getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(String fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Column(name = "usuario_elimina", length = 10)
	public String getUsuarioElimina() {
		return this.usuarioElimina;
	}

	public void setUsuarioElimina(String usuarioElimina) {
		this.usuarioElimina = usuarioElimina;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "ciclo_escolar")
	public Integer getCicloEscolar() {
		return this.cicloEscolar;
	}

	public void setCicloEscolar(Integer cicloEscolar) {
		this.cicloEscolar = cicloEscolar;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "id_curso", nullable = false)
	public int getIdCurso() {
		return this.idCurso;
	}

	public void setIdCurso(int idCurso) {
		this.idCurso = idCurso;
	}

	@Column(name = "id_pensum", nullable = false)
	public int getIdPensum() {
		return this.idPensum;
	}

	public void setIdPensum(int idPensum) {
		this.idPensum = idPensum;
	}

}
