package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Salon generated by hbm2java
 */
@Entity
@Table(name = "salon", catalog = "academitics")
public class Salon implements java.io.Serializable {

	private Integer idSalon;
	private Date fechaEliminacion;
	private String usuarioElimina;
	private Integer sucursal;
	private Date fechaModificacion;
	private Date fechaAdicion;
	private String usuarioModifica;
	private String usuarioAdiciona;
	private Boolean estado;
	private String nombre;
	private Integer cantidadSoportada;
	private Boolean eliminado;

	public Salon() {
	}

	public Salon(Date fechaEliminacion, String usuarioElimina,
			Integer sucursal, Date fechaModificacion, Date fechaAdicion,
			String usuarioModifica, String usuarioAdiciona, Boolean estado,
			String nombre, Integer cantidadSoportada, Boolean eliminado) {
		this.fechaEliminacion = fechaEliminacion;
		this.usuarioElimina = usuarioElimina;
		this.sucursal = sucursal;
		this.fechaModificacion = fechaModificacion;
		this.fechaAdicion = fechaAdicion;
		this.usuarioModifica = usuarioModifica;
		this.usuarioAdiciona = usuarioAdiciona;
		this.estado = estado;
		this.nombre = nombre;
		this.cantidadSoportada = cantidadSoportada;
		this.eliminado = eliminado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_salon", unique = true, nullable = false)
	public Integer getIdSalon() {
		return this.idSalon;
	}

	public void setIdSalon(Integer idSalon) {
		this.idSalon = idSalon;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eliminacion", length = 19)
	public Date getFechaEliminacion() {
		return this.fechaEliminacion;
	}

	public void setFechaEliminacion(Date fechaEliminacion) {
		this.fechaEliminacion = fechaEliminacion;
	}

	@Column(name = "usuario_elimina", length = 10)
	public String getUsuarioElimina() {
		return this.usuarioElimina;
	}

	public void setUsuarioElimina(String usuarioElimina) {
		this.usuarioElimina = usuarioElimina;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "cantidad_soportada")
	public Integer getCantidadSoportada() {
		return this.cantidadSoportada;
	}

	public void setCantidadSoportada(Integer cantidadSoportada) {
		this.cantidadSoportada = cantidadSoportada;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

}
