package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeccionDia generated by hbm2java
 */
@Entity
@Table(name = "seccion_dia", catalog = "academitics")
public class SeccionDia implements java.io.Serializable {

	private Integer idSeccionDia;
	private Date fechaEliminacion;
	private Date fechaAdicion;
	private Date fechaModificacion;
	private String usuarioAdiciona;
	private String usuarioModifica;
	private String usuarioElimina;
	private Integer sucursal;
	private String nombre;
	private Boolean eliminado;
	private int idDia;
	private int idDetallleHorario;
	private int idSalon;
	private int idAsignacionCurso;

	public SeccionDia() {
	}

	public SeccionDia(int idDia, int idDetallleHorario, int idSalon,
			int idAsignacionCurso) {
		this.idDia = idDia;
		this.idDetallleHorario = idDetallleHorario;
		this.idSalon = idSalon;
		this.idAsignacionCurso = idAsignacionCurso;
	}

	public SeccionDia(Date fechaEliminacion, Date fechaAdicion,
			Date fechaModificacion, String usuarioAdiciona,
			String usuarioModifica, String usuarioElimina, Integer sucursal,
			String nombre, Boolean eliminado, int idDia, int idDetallleHorario,
			int idSalon, int idAsignacionCurso) {
		this.fechaEliminacion = fechaEliminacion;
		this.fechaAdicion = fechaAdicion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioAdiciona = usuarioAdiciona;
		this.usuarioModifica = usuarioModifica;
		this.usuarioElimina = usuarioElimina;
		this.sucursal = sucursal;
		this.nombre = nombre;
		this.eliminado = eliminado;
		this.idDia = idDia;
		this.idDetallleHorario = idDetallleHorario;
		this.idSalon = idSalon;
		this.idAsignacionCurso = idAsignacionCurso;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_seccion_dia", unique = true, nullable = false)
	public Integer getIdSeccionDia() {
		return this.idSeccionDia;
	}

	public void setIdSeccionDia(Integer idSeccionDia) {
		this.idSeccionDia = idSeccionDia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eliminacion", length = 19)
	public Date getFechaEliminacion() {
		return this.fechaEliminacion;
	}

	public void setFechaEliminacion(Date fechaEliminacion) {
		this.fechaEliminacion = fechaEliminacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Column(name = "usuario_elimina", length = 10)
	public String getUsuarioElimina() {
		return this.usuarioElimina;
	}

	public void setUsuarioElimina(String usuarioElimina) {
		this.usuarioElimina = usuarioElimina;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "nombre", length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "id_dia", nullable = false)
	public int getIdDia() {
		return this.idDia;
	}

	public void setIdDia(int idDia) {
		this.idDia = idDia;
	}

	@Column(name = "id_detallle_horario", nullable = false)
	public int getIdDetallleHorario() {
		return this.idDetallleHorario;
	}

	public void setIdDetallleHorario(int idDetallleHorario) {
		this.idDetallleHorario = idDetallleHorario;
	}

	@Column(name = "id_salon", nullable = false)
	public int getIdSalon() {
		return this.idSalon;
	}

	public void setIdSalon(int idSalon) {
		this.idSalon = idSalon;
	}

	@Column(name = "id_asignacion_curso", nullable = false)
	public int getIdAsignacionCurso() {
		return this.idAsignacionCurso;
	}

	public void setIdAsignacionCurso(int idAsignacionCurso) {
		this.idAsignacionCurso = idAsignacionCurso;
	}

}
