package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Seccion generated by hbm2java
 */
@Entity
@Table(name = "seccion", catalog = "academitics")
public class Seccion implements java.io.Serializable {

	private Integer idSeccion;
	private Date fechaEliminacion;
	private String usuarioElimina;
	private Date fechaAdicion;
	private Date fechaModficacion;
	private String usuarioAdiciona;
	private String usuarioModifica;
	private Integer sucursal;
	private String cicloEscolar;
	private Boolean eliminado;
	private String nombre;
	private Boolean estado;
	private int idEmpleado;
	private int idCiclo;

	public Seccion() {
	}

	public Seccion(int idEmpleado, int idCiclo) {
		this.idEmpleado = idEmpleado;
		this.idCiclo = idCiclo;
	}

	public Seccion(Date fechaEliminacion, String usuarioElimina,
			Date fechaAdicion, Date fechaModficacion, String usuarioAdiciona,
			String usuarioModifica, Integer sucursal, String cicloEscolar,
			Boolean eliminado, String nombre, Boolean estado, int idEmpleado,
			int idCiclo) {
		this.fechaEliminacion = fechaEliminacion;
		this.usuarioElimina = usuarioElimina;
		this.fechaAdicion = fechaAdicion;
		this.fechaModficacion = fechaModficacion;
		this.usuarioAdiciona = usuarioAdiciona;
		this.usuarioModifica = usuarioModifica;
		this.sucursal = sucursal;
		this.cicloEscolar = cicloEscolar;
		this.eliminado = eliminado;
		this.nombre = nombre;
		this.estado = estado;
		this.idEmpleado = idEmpleado;
		this.idCiclo = idCiclo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_seccion", unique = true, nullable = false)
	public Integer getIdSeccion() {
		return this.idSeccion;
	}

	public void setIdSeccion(Integer idSeccion) {
		this.idSeccion = idSeccion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eliminacion", length = 19)
	public Date getFechaEliminacion() {
		return this.fechaEliminacion;
	}

	public void setFechaEliminacion(Date fechaEliminacion) {
		this.fechaEliminacion = fechaEliminacion;
	}

	@Column(name = "usuario_elimina", length = 10)
	public String getUsuarioElimina() {
		return this.usuarioElimina;
	}

	public void setUsuarioElimina(String usuarioElimina) {
		this.usuarioElimina = usuarioElimina;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modficacion", length = 19)
	public Date getFechaModficacion() {
		return this.fechaModficacion;
	}

	public void setFechaModficacion(Date fechaModficacion) {
		this.fechaModficacion = fechaModficacion;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Column(name = "usuario_modifica", length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "ciclo_escolar", length = 10)
	public String getCicloEscolar() {
		return this.cicloEscolar;
	}

	public void setCicloEscolar(String cicloEscolar) {
		this.cicloEscolar = cicloEscolar;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "nombre", length = 10)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "id_empleado", nullable = false)
	public int getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(int idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	@Column(name = "id_ciclo", nullable = false)
	public int getIdCiclo() {
		return this.idCiclo;
	}

	public void setIdCiclo(int idCiclo) {
		this.idCiclo = idCiclo;
	}

}
