package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoPeriodo generated by hbm2java
 */
@Entity
@Table(name = "tipo_periodo", catalog = "academitics")
public class TipoPeriodo implements java.io.Serializable {

	private String idTipoPeriodo;
	private String nombre;
	private String descripcion;

	public TipoPeriodo() {
	}

	public TipoPeriodo(String idTipoPeriodo) {
		this.idTipoPeriodo = idTipoPeriodo;
	}

	public TipoPeriodo(String idTipoPeriodo, String nombre, String descripcion) {
		this.idTipoPeriodo = idTipoPeriodo;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "id_tipo_periodo", unique = true, nullable = false, length = 10)
	public String getIdTipoPeriodo() {
		return this.idTipoPeriodo;
	}

	public void setIdTipoPeriodo(String idTipoPeriodo) {
		this.idTipoPeriodo = idTipoPeriodo;
	}

	@Column(name = "nombre", length = 10)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 10)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
