package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoEmpleado generated by hbm2java
 */
@Entity
@Table(name = "tipo_empleado", catalog = "academitics")
public class TipoEmpleado implements java.io.Serializable {

	private Integer idTipoEmpleado;
	private Integer sucursal;
	private Boolean estado;
	private String nombre;
	private String descripcion;
	private Boolean eliminado;

	public TipoEmpleado() {
	}

	public TipoEmpleado(Integer sucursal, Boolean estado, String nombre,
			String descripcion, Boolean eliminado) {
		this.sucursal = sucursal;
		this.estado = estado;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.eliminado = eliminado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_tipo_empleado", unique = true, nullable = false)
	public Integer getIdTipoEmpleado() {
		return this.idTipoEmpleado;
	}

	public void setIdTipoEmpleado(Integer idTipoEmpleado) {
		this.idTipoEmpleado = idTipoEmpleado;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "nombre", length = 250)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

}
