package com.academitics.mapeo;

// Generated 10/06/2016 05:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoCiclo generated by hbm2java
 */
@Entity
@Table(name = "tipo_ciclo", catalog = "academitics")
public class TipoCiclo implements java.io.Serializable {

	private int idTipoCiclo;
	private Boolean eliminado;
	private Integer ciclosMax;
	private String nombre;
	private String descripcion;
	private Integer sucursal;
	private String usuarioModifica;
	private String usuarioElimina;
	private String usuarioAdiciona;
	private Date fechaModificacion;
	private Date fechaEliminacion;
	private Date fechaAdicion;
	private int idNivel;

	public TipoCiclo() {
	}

	public TipoCiclo(int idTipoCiclo, String descripcion,
			String usuarioModifica, int idNivel) {
		this.idTipoCiclo = idTipoCiclo;
		this.descripcion = descripcion;
		this.usuarioModifica = usuarioModifica;
		this.idNivel = idNivel;
	}

	public TipoCiclo(int idTipoCiclo, Boolean eliminado, Integer ciclosMax,
			String nombre, String descripcion, Integer sucursal,
			String usuarioModifica, String usuarioElimina,
			String usuarioAdiciona, Date fechaModificacion,
			Date fechaEliminacion, Date fechaAdicion, int idNivel) {
		this.idTipoCiclo = idTipoCiclo;
		this.eliminado = eliminado;
		this.ciclosMax = ciclosMax;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.sucursal = sucursal;
		this.usuarioModifica = usuarioModifica;
		this.usuarioElimina = usuarioElimina;
		this.usuarioAdiciona = usuarioAdiciona;
		this.fechaModificacion = fechaModificacion;
		this.fechaEliminacion = fechaEliminacion;
		this.fechaAdicion = fechaAdicion;
		this.idNivel = idNivel;
	}

	@Id
	@Column(name = "id_tipo_ciclo", unique = true, nullable = false)
	public int getIdTipoCiclo() {
		return this.idTipoCiclo;
	}

	public void setIdTipoCiclo(int idTipoCiclo) {
		this.idTipoCiclo = idTipoCiclo;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "ciclos_max")
	public Integer getCiclosMax() {
		return this.ciclosMax;
	}

	public void setCiclosMax(Integer ciclosMax) {
		this.ciclosMax = ciclosMax;
	}

	@Column(name = "nombre", length = 10)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false, length = 55)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "usuario_modifica", nullable = false, length = 10)
	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Column(name = "usuario_elimina", length = 10)
	public String getUsuarioElimina() {
		return this.usuarioElimina;
	}

	public void setUsuarioElimina(String usuarioElimina) {
		this.usuarioElimina = usuarioElimina;
	}

	@Column(name = "usuario_adiciona", length = 10)
	public String getUsuarioAdiciona() {
		return this.usuarioAdiciona;
	}

	public void setUsuarioAdiciona(String usuarioAdiciona) {
		this.usuarioAdiciona = usuarioAdiciona;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eliminacion", length = 19)
	public Date getFechaEliminacion() {
		return this.fechaEliminacion;
	}

	public void setFechaEliminacion(Date fechaEliminacion) {
		this.fechaEliminacion = fechaEliminacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adicion", length = 19)
	public Date getFechaAdicion() {
		return this.fechaAdicion;
	}

	public void setFechaAdicion(Date fechaAdicion) {
		this.fechaAdicion = fechaAdicion;
	}

	@Column(name = "id_nivel", nullable = false)
	public int getIdNivel() {
		return this.idNivel;
	}

	public void setIdNivel(int idNivel) {
		this.idNivel = idNivel;
	}

}
